// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using OrderFlow.Console.Persistence;

#nullable disable

namespace OrderFlow.Console.Migrations;

[DbContext(typeof(OrderFlowContext))]
partial class OrderFlowContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("OrderFlow.Console.Models.Customer", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("City").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Email").HasColumnType("TEXT");
            b.Property<string>("FullName").IsRequired().HasColumnType("TEXT");
            b.Property<bool>("IsVIP").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("FullName").HasDatabaseName("IX_Customers_FullName");
            b.ToTable("Customers");
        });

        modelBuilder.Entity("OrderFlow.Console.Models.Product", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("Category").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
            b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("TEXT");
            b.Property<int>("Stock").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.ToTable("Products");
        });

        modelBuilder.Entity("OrderFlow.Console.Models.Order", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("CustomerId").HasColumnType("INTEGER");
            b.Property<DateTime>("Date").HasColumnType("TEXT");
            b.Property<string>("Notes").HasColumnType("TEXT");
            b.Property<int>("Status").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("CustomerId").HasDatabaseName("IX_Orders_CustomerId");
            b.HasIndex("Status").HasDatabaseName("IX_Orders_Status");
            b.ToTable("Orders");
        });

        modelBuilder.Entity("OrderFlow.Console.Models.OrderItem", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("OrderId").HasColumnType("INTEGER");
            b.Property<int>("ProductId").HasColumnType("INTEGER");
            b.Property<int>("Quantity").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("OrderId").HasDatabaseName("IX_OrderItems_OrderId");
            b.HasIndex("ProductId").HasDatabaseName("IX_OrderItems_ProductId");
            b.ToTable("OrderItems");
        });

        modelBuilder.Entity("OrderFlow.Console.Models.Order", b =>
        {
            b.HasOne("OrderFlow.Console.Models.Customer", "Customer")
                .WithMany("Orders")
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.Navigation("Customer");
        });

        modelBuilder.Entity("OrderFlow.Console.Models.OrderItem", b =>
        {
            b.HasOne("OrderFlow.Console.Models.Product", "Product")
                .WithMany()
                .HasForeignKey("ProductId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.HasOne("OrderFlow.Console.Models.Order", null)
                .WithMany("Items")
                .HasForeignKey("OrderId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Product");
        });

        modelBuilder.Entity("OrderFlow.Console.Models.Customer", b =>
        {
            b.Navigation("Orders");
        });

        modelBuilder.Entity("OrderFlow.Console.Models.Order", b =>
        {
            b.Navigation("Items");
        });
#pragma warning restore 612, 618
    }
}
